matrix:
  include:
  - os: linux
    language: android
    android:
      components:
        - build-tools-28.0.3
        - android-28
      licenses:
        - 'android-sdk-preview-license-52d11cd2'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
    jdk: oraclejdk8
    env:
      KBUILD=linux-chrome-android
      JAVA_OPTS=-Xmx2g
    before_install:
      - mkdir "$ANDROID_HOME/licenses" || true && echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
      - yes | /usr/local/android-sdk/tools/bin/sdkmanager --licenses
    script:
    - ./gradlew -s -i assemble check jsTestChrome lint testDebugUnitTest
  - os: windows
    env: KBUILD=windows
    language: shell # java is not supported but jdk is installed
    script:
    - powershell -Command "cmd /c travis_win.bat"
  - os: osx
    env:
      KBUILD=macos
      JAVA_OPTS=-Xmx2g
    language: java
    jdk: openjdk10
    before_install:
    - cp $(/usr/libexec/java_home)/lib/security/cacerts "${JAVA_HOME}/lib/security/cacerts"
    script:
    - ./gradlew -s -i check build
