name: VERSIONINGTEST

on:
  push:
    tags:
      - 'v*'

env:
  FORCED_VERSION: ${{ github.ref }}
  BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
  BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}

jobs:
  publishVersionNumbers:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository name
        run:  echo "::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')"

      - name: Get version
        run:  echo "::set-env name=VERSION::${GITHUB_REF/refs\/tags\/v/}"

      - name: Get current branch
        run:  echo "::set-env name=CURRENTBRANCH::${GITHUB_REF##*/}"

      - name: Checkout korlibs-versions repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.KORGEBOT_TOKEN }}
          repository: korlibs/korlibs-versions
          ref: ${{ env.CURRENTBRANCH }}

      - name: Bump version numbers
        run: |
          sed -i 's/'$REPOSITORY_NAME'Version=.*/'$REPOSITORY_NAME'Version='$VERSION'/g' versions.ver
          git config --global user.email "githubactionsbot@korge.org"
          git config --global user.name "korgebot"
          git add versions.ver
          git commit -m "${{ env.REPOSITORY_NAME }} bump to ${{ env.VERSION }}" -m "Bumped ${{ env.REPOSITORY_NAME }} version number to ${{ env.VERSION }}"
          git push
